### ISSUE TITLE
Labels not available.

### ISSUE THREAD

**Issue by Adeelyousaf** [EgocentricVision/N-EPIC-Kitchens#1]
Hi,

I found your work E2(GO)MOTION very intriguing, and I am reading your work in detail.  And, I also appreciate your efforts for creating and  sharing the dataset.

Kindly, if you could upload the labels also. Or if you can share specifics how you created the labels from the RGB version of EPIC Kitchen dataset.

**Comment by plana93** [comment]
Hi,

Thank you for your interest. We have avoided uploading the annotations because they are the same as the original Epic Kitchens dataset, but they may be good to have on this repository (uploaded them right now). 

You may also get them here https://github.com/jonmun/MM-SADA-code/tree/master/Annotations
